src/main/java/edu/ucsb/cs156/example/controllers/MenuItemReviewController.java
src/main/java/edu/ucsb/cs156/example/entities/MenuItemReview.java
src/main/java/edu/ucsb/cs156/example/repositories/MenuItemReviewRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/MenuItemReviewControllerTests.java

Copied over backend files from team02
Files: 
- MenuItemReview.java
- MenuItemReviewRepository.java
- MenuItemReviewController.java
- MenuItemReviewControllerTests.java
Closes #35

ln - Copy files for backend CRUD API MenuItemReview

---

frontend/src/fixtures/menuItemReviewFixtures.js
src/main/java/edu/ucsb/cs156/example/controllers/MenuItemReviewController.java
src/main/java/edu/ucsb/cs156/example/entities/MenuItemReview.java
src/main/java/edu/ucsb/cs156/example/repositories/MenuItemReviewRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/MenuItemReviewControllerTests.java

Created MenuItemReview fixtures
#Closes 36

ln - Created MenuItemReview fixtures  

---

frontend/src/App.js
frontend/src/fixtures/ucsbOrganizationFixtures.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/components/UCSBOrganization/UCSBOrganizationForm.js
frontend/src/main/components/UCSBOrganization/UCSBOrganizationTable.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationCreatePage.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationEditPage.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationIndexPage.js
frontend/src/main/utils/UCSBOrganizationUtils.js
frontend/src/stories/components/UCSBOrganization/UCSBOrganizationForm.stories.js
frontend/src/stories/components/UCSBOrganization/UCSBOrganizationTable.stories.js
frontend/src/stories/pages/UCSBOrganization/UCSBOrganizationCreatePage.stories.js
frontend/src/stories/pages/UCSBOrganization/UCSBOrganizationEditPage.stories.js
frontend/src/stories/pages/UCSBOrganization/UCSBOrganizationIndexPage.stories.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationForm.test.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationTable.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationCreatePage.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationEditPage.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationIndexPage.test.js
src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationControllerTests.java

I implemented the edit page where the user has the option to edit existing organizations and submit the updates so it changes on the table. I also implemented tests for the EditPage and stories.
Link to storyboard: http://localhost:6006/?path=/story/pages-ucsborganization-ucsborganizationeditpage--default

eh - UCSBOrganization edit page + tests

---

src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationControllerTests.java

Copied the @Entity, @Repository, Controller, and Controller tests for UCSBOrganization over from team02
Closes #17

eh - Copy files for backend CRUD API UCSBOrganization

---

frontend/src/fixtures/ucsbOrganizationFixtures.js
src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationControllerTests.java

I created a file called ucsbOrganizationFixtures.js that contains Javascript fixtures
for the database table
Closes #18

eh - Created UCSBOrganization fixtures

---

frontend/src/fixtures/ucsbOrganizationFixtures.js
frontend/src/main/components/UCSBOrganization/UCSBOrganizationForm.js
frontend/src/stories/components/UCSBOrganization/UCSBOrganizationForm.stories.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationForm.test.js
src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationControllerTests.java

I created the UCSBOrganization Form component, tests for UCSBOrganizationForm.js, and UCSBOrganizationForm.stories.js.
Closes #19

eh - UCSBOrganization Form Component

---

frontend/src/fixtures/ucsbOrganizationFixtures.js
frontend/src/main/components/UCSBOrganization/UCSBOrganizationForm.js
frontend/src/main/components/UCSBOrganization/UCSBOrganizationTable.js
frontend/src/stories/components/UCSBOrganization/UCSBOrganizationForm.stories.js
frontend/src/stories/components/UCSBOrganization/UCSBOrganizationTable.stories.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationForm.test.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationTable.test.js
src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationControllerTests.java

I created UCSBOrganizationTable, UCSBOrganizationTable.test.js, 
UCSBOrganizationTable.stories.js which implements the UCSBOrganizationTable and tests to to test the functionality of it. 
Closes #20

eh - UCSBOrganization table component

---

frontend/src/App.js
frontend/src/fixtures/ucsbOrganizationFixtures.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/components/UCSBOrganization/UCSBOrganizationForm.js
frontend/src/main/components/UCSBOrganization/UCSBOrganizationTable.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationCreatePage.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationEditPage.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationIndexPage.js
frontend/src/stories/components/UCSBOrganization/UCSBOrganizationForm.stories.js
frontend/src/stories/components/UCSBOrganization/UCSBOrganizationTable.stories.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationForm.test.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationTable.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationCreatePage.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationEditPage.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationIndexPage.test.js
src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationControllerTests.java

I set up placeholders for the UCSBOrganization pages I am adding to the app.
Closes #21

eh - UCSBOrganization page placeholders

---

frontend/src/App.js
frontend/src/fixtures/ucsbOrganizationFixtures.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/components/UCSBOrganization/UCSBOrganizationForm.js
frontend/src/main/components/UCSBOrganization/UCSBOrganizationTable.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationCreatePage.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationEditPage.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationIndexPage.js
frontend/src/stories/components/UCSBOrganization/UCSBOrganizationForm.stories.js
frontend/src/stories/components/UCSBOrganization/UCSBOrganizationTable.stories.js
frontend/src/stories/pages/UCSBOrganization/UCSBOrganizationCreatePage.stories.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationForm.test.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationTable.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationCreatePage.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationEditPage.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationIndexPage.test.js
src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationControllerTests.java

I implemented the code for users to create a new UCSBOrganization record, tests for UCSBOrganizationCreatePage, and the story for it.
Steps to test the new page:
(1) Log in to http://localhost:8080/ucsborganization/edit/1
(2) Click on the UCSBOrganization tab
(3) Locate the create link to open the create page
(4) Enter string values for orgCode, orgTranslationShort, and orgTranslation. Select from "True" or "False" using the dropdown box to choose the organization's inactive status. 
(5) Click Create. Upon correct parameter formats entered, the new organization will be created. 
968/693aa118-3091-4b5a-84fd-931cb605410b">
Link to the storybook entry for the new page: http://localhost:6006/?path=/story/pages-ucsborganization-ucsborganizationcreatepage--default
Closes #22

eh - UCSBOrganization create page

---

frontend/src/App.js
frontend/src/fixtures/ucsbOrganizationFixtures.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/components/UCSBOrganization/UCSBOrganizationForm.js
frontend/src/main/components/UCSBOrganization/UCSBOrganizationTable.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationCreatePage.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationEditPage.js
frontend/src/main/pages/UCSBOrganization/UCSBOrganizationIndexPage.js
frontend/src/main/utils/UCSBOrganizationUtils.js
frontend/src/stories/components/UCSBOrganization/UCSBOrganizationForm.stories.js
frontend/src/stories/components/UCSBOrganization/UCSBOrganizationTable.stories.js
frontend/src/stories/pages/UCSBOrganization/UCSBOrganizationCreatePage.stories.js
frontend/src/stories/pages/UCSBOrganization/UCSBOrganizationIndexPage.stories.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationForm.test.js
frontend/src/tests/components/UCSBOrganization/UCSBOrganizationTable.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationCreatePage.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationEditPage.test.js
frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationIndexPage.test.js
src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationControllerTests.java

I implemented the functionality on the frontend for UCSBOrganization Index Page, the tests to check the functionality is performing as expected, and the story for IndexPage.
Link to published storybook for PR: http://localhost:6006/?path=/story/pages-ucsborganization-ucsborganizationindexpage--empty
Closes #23

eh -  UCSBOrganization index page + tests + stories

---

frontend/src/fixtures/menuItemReviewFixtures.js
frontend/src/main/components/MenuItemReviews/MenuItemReviewForm.js
frontend/src/stories/components/MenuItemReviews/MenuItemReviewForm.stories.js
frontend/src/tests/components/MenuItemReviews/MenuItemReviewForm.test.js
src/main/java/edu/ucsb/cs156/example/controllers/MenuItemReviewController.java
src/main/java/edu/ucsb/cs156/example/entities/MenuItemReview.java
src/main/java/edu/ucsb/cs156/example/repositories/MenuItemReviewRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/MenuItemReviewControllerTests.java

Created the MenuItemReview Form component, tests for MenuItemReviewForm.js, and MenuItemReviewForm.stories.js.
Closes #37

ln - MenuItemReview Form Component

---

src/main/java/edu/ucsb/cs156/example/controllers/HelpRequestController.java
src/main/java/edu/ucsb/cs156/example/entities/HelpRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/HelpRequestRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/HelpRequestControllerTests.java

In this PR, I added all the HelpRequest backend files (HelpRequest.java, HelpRequestRepository.java, HelpRequestController.java, and HelpRequestControllerTests.java).
Closes #44

KV - Copy files for Backend CRUD API HelpRequest from team02

---

src/main/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBDiningCommonsMenuItem.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBDiningCommonsMenuItemRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemControllerTests.java

In this PR, I copied over the backend CRUD operations for UCSBDiningCommonsMenuItem from team02.
Deployed at: https://team03-ashton-wong-dev.dokku-14.cs.ucsb.edu
Closes #8

AW - Added Backend CRUD Operations for Menu Items

---

frontend/src/fixtures/helpRequestFixtures.js
src/main/java/edu/ucsb/cs156/example/controllers/HelpRequestController.java
src/main/java/edu/ucsb/cs156/example/entities/HelpRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/HelpRequestRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/HelpRequestControllerTests.java

In this PR, I created the helpRequestfixtures.js file that consists of 4 different help requests.
Closes #45

KV - Create fixtures for HelpRequest

---

frontend/src/fixtures/recommendationRequestFixtures.js
frontend/src/main/components/RecommendationRequests/RecommendationRequestForm.js
frontend/src/stories/components/RecommendationRequests/RecommendationRequestForm.stories.js
frontend/src/tests/components/RecommendationRequests/RecommendationRequestForm.test.js
src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestController.java
src/main/java/edu/ucsb/cs156/example/entities/RecommendationRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/RecommendationRequestRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestControllerTests.java

Form and tests for ReqRequest
Closes #28

Andy req request form comp

---

src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestController.java
src/main/java/edu/ucsb/cs156/example/entities/RecommendationRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/RecommendationRequestRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestControllerTests.java

AG - copied backend over from team02 and check CRUD in swagger
Closes#26

Andy backend copy

---

frontend/src/fixtures/recommendationRequestFixtures.js
src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestController.java
src/main/java/edu/ucsb/cs156/example/entities/RecommendationRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/RecommendationRequestRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestControllerTests.java

AG - added recommendationRequestFixtures.js file
Closes #27

Andy req request fixtures

---

frontend/src/fixtures/ucsbDiningCommonsMenuItemFixtures.js
src/main/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemController.java
src/main/java/edu/ucsb/cs156/example/entities/UCSBDiningCommonsMenuItem.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBDiningCommonsMenuItemRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemControllerTests.java

In this PR, I added the fixtures file for DiningCommonsMenuItem.
Deployed at: https://team03-ashton-wong-dev.dokku-14.cs.ucsb.edu
Closes #9

AW - Fixtures for Menu Items

---

frontend/src/fixtures/ucsbDiningCommonsMenuItemFixtures.js
frontend/src/main/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.js
frontend/src/stories/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.stories.js
frontend/src/tests/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.test.js

In this PR, I added the form components for UCSBDiningCommonsMenuItem and respective tests that passed both mutation and coverage tests.
Closes #10

AW - Menu Item Form Components + Tests

---

frontend/src/fixtures/ucsbDiningCommonsMenuItemFixtures.js
frontend/src/main/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.js
frontend/src/main/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemTable.js
frontend/src/main/utils/UCSBDiningCommonsMenuItemUtils.js
frontend/src/stories/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.stories.js
frontend/src/stories/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemTable.stories.js
frontend/src/tests/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.test.js
frontend/src/tests/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemTable.test.js
frontend/src/tests/utils/UCSBDiningCommonsMenuItemUtils.test.js

In this PR, I added the table component for menu items and related tests, which pass mutation and coverage tests.
Closes #11

AW - Added Table Component For Menu Items

---

src/main/java/edu/ucsb/cs156/example/controllers/ArticlesController.java
src/main/java/edu/ucsb/cs156/example/entities/Articles.java
src/main/java/edu/ucsb/cs156/example/repositories/ArticlesRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/ArticlesControllerTests.java

copied files for backend CRUF API Articles from team02 and successfully tested Article CRUD operations on Swagger
closes #53

mw - copied files for backend CRUF API Articles from team02

---

frontend/src/fixtures/articlesFixtures.js
src/main/java/edu/ucsb/cs156/example/controllers/ArticlesController.java
src/main/java/edu/ucsb/cs156/example/entities/Articles.java
src/main/java/edu/ucsb/cs156/example/repositories/ArticlesRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/ArticlesControllerTests.java

added fixtures for Articles
closes #54

mw - added fixtures for Articles

---

frontend/src/fixtures/helpRequestFixtures.js
frontend/src/main/components/HelpRequest/HelpRequestForm.js
frontend/src/stories/components/HelpRequest/HelpRequestForm.stories.js
frontend/src/tests/components/HelpRequest/HelpRequestForm.test.js
src/main/java/edu/ucsb/cs156/example/controllers/HelpRequestController.java
src/main/java/edu/ucsb/cs156/example/entities/HelpRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/HelpRequestRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/HelpRequestControllerTests.java

In this PR, I created the HelpRequestForm component and added tests for it. I also created a storybook for HelpRequest.
https://ucsb-cs156-w24.github.io/team03-w24-7pm-2/prs/146/storybook
Closes #46

KV -  Form Component for HelpRequest plus tests

---

frontend/src/fixtures/helpRequestFixtures.js
frontend/src/main/components/HelpRequest/HelpRequestForm.js
frontend/src/main/components/HelpRequest/HelpRequestTable.js
frontend/src/main/utils/HelpRequestUtils.js
frontend/src/stories/components/HelpRequest/HelpRequestForm.stories.js
frontend/src/tests/components/HelpRequest/HelpRequestForm.test.js
frontend/src/tests/components/HelpRequest/HelpRequestTable.test.js
frontend/src/tests/utils/HelpRequestUtils.test.js
src/main/java/edu/ucsb/cs156/example/controllers/HelpRequestController.java
src/main/java/edu/ucsb/cs156/example/entities/HelpRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/HelpRequestRepository.java
src/test/java/edu/ucsb/cs156/example/controllers/HelpRequestControllerTests.java

In this PR, I added the HelpRequest table component along with tests, and the HelpRequest utils file and its tests.
Closes #47

KV - Table Component for HelpRequest plus tests (new pull request)

---

frontend/src/App.js
frontend/src/main/components/HelpRequest/HelpRequestForm.js
frontend/src/main/components/HelpRequest/HelpRequestTable.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/pages/HelpRequest/HelpRequestCreatePage.js
frontend/src/main/pages/HelpRequest/HelpRequestEditPage.js
frontend/src/main/pages/HelpRequest/HelpRequestIndexPage.js
frontend/src/main/utils/HelpRequestUtils.js
frontend/src/stories/components/HelpRequest/HelpRequestForm.stories.js
frontend/src/tests/components/HelpRequest/HelpRequestForm.test.js
frontend/src/tests/components/HelpRequest/HelpRequestTable.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestCreatePage.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestEditPage.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestIndexPage.test.js
frontend/src/tests/utils/HelpRequestUtils.test.js

In this PR, I added HelpRequest pages, and added the /helprequest route to App.js and nav link to AppNavbar.js.
Closes #48

KV - Copy Placeholders for HelpRequest pages; add to App.js/AppNavbar.js

---

frontend/src/App.js
frontend/src/main/components/HelpRequest/HelpRequestForm.js
frontend/src/main/components/HelpRequest/HelpRequestTable.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/pages/HelpRequest/HelpRequestCreatePage.js
frontend/src/main/pages/HelpRequest/HelpRequestEditPage.js
frontend/src/main/pages/HelpRequest/HelpRequestIndexPage.js
frontend/src/main/utils/HelpRequestUtils.js
frontend/src/stories/components/HelpRequest/HelpRequestForm.stories.js
frontend/src/stories/components/HelpRequest/HelpRequestTable.stories.js
frontend/src/tests/components/HelpRequest/HelpRequestForm.test.js
frontend/src/tests/components/HelpRequest/HelpRequestTable.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestCreatePage.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestEditPage.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestIndexPage.test.js
frontend/src/tests/utils/HelpRequestUtils.test.js

In this PR, I created HelpRequestCreatePage and ran tests on it. I also add the story for HelpRequestTable in this commit.
Closes #49

KV - Create Page for HelpRequest plus tests and stories

---

frontend/src/App.js
frontend/src/fixtures/helpRequestFixtures.js
frontend/src/main/components/HelpRequest/HelpRequestForm.js
frontend/src/main/components/HelpRequest/HelpRequestTable.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/pages/HelpRequest/HelpRequestCreatePage.js
frontend/src/main/pages/HelpRequest/HelpRequestEditPage.js
frontend/src/main/pages/HelpRequest/HelpRequestIndexPage.js
frontend/src/main/utils/HelpRequestUtils.js
frontend/src/stories/components/HelpRequest/HelpRequestForm.stories.js
frontend/src/stories/components/HelpRequest/HelpRequestTable.stories.js
frontend/src/tests/components/HelpRequest/HelpRequestForm.test.js
frontend/src/tests/components/HelpRequest/HelpRequestTable.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestCreatePage.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestEditPage.test.js
frontend/src/tests/pages/HelpRequest/HelpRequestIndexPage.test.js
frontend/src/tests/utils/HelpRequestUtils.test.js

In this PR, I added HelpRequestIndexPage and tests, and fixed a typo in helpRequestFixtures.
Closes #50

KV - Index Page for HelpRequest plus tests and stories

---

frontend/src/main/pages/Articles/ArticlesEditPage.js
frontend/src/stories/pages/Articles/ArticlesEditPage.stories.js
frontend/src/tests/pages/Articles/ArticlesEditPage.test.js

Added articles edit page, tests, and stories
closes #60

mw - added articles edit page, tests, and stories
